import type { Metadata } from "next";
// import { Geist, Geologica } from "next/font/google";
import { Geologica } from "next/font/google";
import "./globals.css";

const geologica = Geologica ({
  variable: "--font-geologica",
  subsets: ["latin"]
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Nexus Leet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geologica.variable} ${geistSans.variable}`}> */}
      <body className={`${geologica.variable}`}>
        {children}
      </body>
    </html>
  );
}
